### ISSUE TITLE
witcheryの大釜でのネザーウォート作成が失敗する事案

### ISSUE THREAD

**Issue by kurosemi** [finalcity/SERVER_files#4]
タイトル通り。
魔力も参照範囲も足りているのに失敗する。
一瞬成功エフェクトが出たのでもう少し検証の必要あり？

**Comment by kurosemi** [comment]
クリエイティブのシングルで試したところ成功

**Comment by a0n0** [comment]
検討つかないな.......
singleでいけてmultiでできないってpluginの影響ってパターンが多いけどそんな項目は思いつかない。謎度高め。もう少しあの手この手で検証続けてほしい　こっちも調べとく。


そしてこちらに移設>>>>>
https://github.com/finalcity/SERVER_dev/issues
